import { NextRequest, NextResponse } from 'next/server';
import { ProjectData } from '@/lib/types';

export async function POST(request: NextRequest) {
  try {
    const { projectData }: { projectId?: string; projectData: ProjectData } = await request.json();
    
    if (!projectData || !projectData.files || projectData.files.length === 0) {
      return NextResponse.json(
        { error: 'No project data or files found' },
        { status: 400 }
      );
    }

    // Create a simple ZIP-like structure using JSZip alternative
    const files: Record<string, string> = {};
    
    // Add all project files
    projectData.files.forEach(file => {
      files[file.path] = file.content;
    });

    // Add package.json if it's a JavaScript/TypeScript project
    if (projectData.language === 'javascript' || projectData.language === 'typescript') {
      const packageJson = {
        name: projectData.name.toLowerCase().replace(/[^a-z0-9-]/g, '-'),
        version: '1.0.0',
        description: projectData.description,
        main: 'index.js',
        scripts: {
          start: 'node index.js',
          dev: 'node index.js',
          build: 'echo "Build complete"'
        },
        keywords: projectData.tags,
        author: 'Blackbox AI Agent',
        license: 'MIT'
      };
      
      if (!files['package.json']) {
        files['package.json'] = JSON.stringify(packageJson, null, 2);
      }
    }

    // Add README.md
    if (!files['README.md']) {
      const readme = `# ${projectData.name}

${projectData.description}

## Generated by Blackbox AI Agent

This project was generated using the Blackbox AI Agent.

### Project Details
- **Language**: ${projectData.language}
${projectData.framework ? `- **Framework**: ${projectData.framework}` : ''}
- **Created**: ${new Date(projectData.createdAt).toLocaleDateString()}
- **Files**: ${projectData.files.length}

### Tags
${projectData.tags.map(tag => `- ${tag}`).join('\n')}

### Getting Started

1. Extract the project files
2. Install dependencies (if applicable)
3. Run the application

### Files Structure

${projectData.files.map(file => `- \`${file.path}\` (${file.language})`).join('\n')}

---

*Generated with ❤️ by Blackbox AI Agent*
`;
      files['README.md'] = readme;
    }

    // Create a simple archive response
    const archiveContent = createSimpleArchive(files);
    
    return new Response(archiveContent, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="${projectData.name.replace(/[^a-zA-Z0-9-]/g, '-')}.txt"`,
      },
    });
    
  } catch (error) {
    console.error('Download API error:', error);
    
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Download failed' },
      { status: 500 }
    );
  }
}

// Simple archive creation (basic implementation)
function createSimpleArchive(files: Record<string, string>): string {
  // This is a simplified implementation
  // In a real application, you'd use JSZip or similar
  
  let content = '';
  
  // Create a simple text-based archive format
  content += '# BLACKBOX AI PROJECT ARCHIVE\n';
  content += '# Extract using any text editor\n';
  content += '# Each file is separated by "=== FILE: filename ==="\n\n';
  
  Object.entries(files).forEach(([path, fileContent]) => {
    content += `=== FILE: ${path} ===\n`;
    content += fileContent;
    content += '\n\n';
  });
  
  content += '=== END OF ARCHIVE ===\n';
  
  // For a real ZIP file, you would use JSZip:
  /*
  const JSZip = require('jszip');
  const zip = new JSZip();
  
  Object.entries(files).forEach(([path, content]) => {
    zip.file(path, content);
  });
  
  return zip.generateAsync({ type: 'uint8array' });
  */
  
  return content;
}

export async function GET() {
  return NextResponse.json(
    { 
      message: 'Project Download API',
      description: 'POST with projectId and projectData to download project as ZIP'
    },
    { status: 200 }
  );
}